name: Sync Dev Branch

on:
  push:
    branches:
      - main

jobs:
  sync-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync dev with main
        run: |
          git checkout main
          git pull origin main
          git checkout dev
          git reset --hard main
          git push origin dev --force
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
