name: Sync Dev Branch

on:
  push:
    branches:
      - main

jobs:
  sync-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.ACTION_KEY }}

      - name: Sync dev with main
        run: |
          git fetch origin
          git checkout dev
          git reset --hard main
          git push origin dev --force
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
